server:
   servlet:
      contextPath: /auth-service
   port: 8089

#DB Config
spring:
   application:
      name: auth
   main:
      allow-bean-definition-overriding: true
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://mypostgres:5432/telecounselor?serverTimezone=UTC
      username : postgres
      password : root
   jpa:
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
   client:
      serviceUrl:
         defaultZone: http://servicediscovery:8761/eureka/

app:
   public-key: public_key.der
   private-key: private_key.der
   login-time-limit-in-hour: ${LOGIN_TIME_LIMIT_IN_HOUR:1}
   login-count-limit: ${LOGIN_COUNT_LIMIT:5}
